import '@/src/app/base.css'
import Navigation from '@/src/components/base/navigation/Navigation';
import { getAuthenticatedAppForUser } from "@/src/lib/firebase/serverApp";

const navigation = [
    { name: 'Product', href: '#' },
    { name: 'Features', href: '#' },
    { name: 'Marketplace', href: '#' },
    { name: 'Company', href: '#' },
  ];

export const metadata = {
  title: 'My Awesome App',
  description: 'Generated by create next app',
}

export default async function DemoLayout({ children }) {
  const { currentUser } = await getAuthenticatedAppForUser();
  return (
    <html lang="en">
      <body>
        <Navigation navigation={navigation}/>
        {children}
      </body>
    </html>
  )
}
