import '@/src/app/base.css'
import Navigation from '@/src/components/base/navigation/Navigation';
import { getAuthenticatedAppForUser } from "@/src/lib/firebase/serverApp";

const navigation = [
    { name: 'Recaps', href: '/recaps' },
    { name: 'Recap', href: '/recap/1234' },
    { name: 'AdminRe', href: '/recap/1234/admin' },
    { name: 'Dashboard', href: '/dashboard' },
    { name: 'Settings', href: '/settings' },
  ];

export const metadata = {
  title: 'My Awesome App',
  description: 'Generated by create next app',
}

export default async function DemoLayout({ children }) {
  const { currentUser } = await getAuthenticatedAppForUser();
  return (
    <html lang="en">
      <body>
        <Navigation navigation={navigation}/>
        {children}
      </body>
    </html>
  )
}
