import '@/src/app/base.css'
import Navigation from '@/src/components/base/navigation/Navigation';
import Navbar from '@/src/components/base/navigation/Navbar';
import { getAuthenticatedAppForUser } from "@/src/lib/firebase/serverApp";
import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
import {notFound} from 'next/navigation';
import {routing} from '@/src/i18n/routing';

const navigation = [
    { name: 'Recaps', href: '/recaps' },
    { name: 'Recap', href: '/recap/1234' },
    { name: 'AdminRe', href: '/recap/1234/admin' },
    { name: 'Dashboard', href: '/dashboard' },
    { name: 'Settings', href: '/settings' },
  ];

export const dynamic = "force-dynamic";

export const metadata = {
  title: 'My Awesome App',
  description: 'Generated by create next app',
}

{/* <Navigation 
initialUser={currentUser?.toJSON()} navigation={navigation}
/> */}

export default async function DemoLayout({
  children,
  params: {locale}
}) {
  if (!routing.locales.includes(locale)) {
    notFound();
  }
  const { currentUser } = await getAuthenticatedAppForUser();

  const messages = await getMessages();
  // debugger
  return (
    <html lang={locale}>
      <body>
      <NextIntlClientProvider messages={messages}>
        <Navigation
          initialUser={currentUser?.toJSON()} navigation={navigation}
        />
        {children}
      </NextIntlClientProvider>
      </body>
    </html>
  )
}
